#!/bin/bash
# ============================================================
# TérangaOS — Edition configuration variables
# This file is AUTO-GENERATED by setup-rpi.sh from
# config/editions.json. Do not edit manually.
# ============================================================

# Identity
export TERANGA_EDITION="rpi"
export TERANGA_NAME="TérangaOS RPi Edition"
export TERANGA_VERSION="0.1"
export TERANGA_CODENAME="Diamniadio"
export TERANGA_HOSTNAME="terangaos-rpi"

# Architecture and target
export TERANGA_ARCH="arm64"
export TERANGA_DESKTOP="xfce"

# Appearance
export TERANGA_THEME="Fluent-Dark"
export TERANGA_ICONS="Fluent"
export TERANGA_FONT="Inter 11"
export TERANGA_CURSOR="Bibata-Modern-Classic"
export TERANGA_WALLPAPER="dakar-sunset"

# Localization
export TERANGA_LANG="fr_FR.UTF-8"
export TERANGA_TIMEZONE="Africa/Dakar"
export TERANGA_KEYBOARD="fr"

# Output
export TERANGA_OUTPUT="terangaos-0.1-rpi-arm64"
