#!/bin/bash
# ============================================================
# TérangaOS — Setup orchestrator (modular system)
#
# Usage:
#   sudo bash scripts/setup-rpi.sh           → complete installation
#   sudo bash scripts/setup-rpi.sh --mod 05  → only mod 05
#   sudo bash scripts/setup-rpi.sh --list    → list mods
#
# Architecture inspired by AnduinOS (github.com/Anduin2017/AnduinOS)
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
MODS_DIR="${REPO_ROOT}/src/mods"
ARGS_SH="${REPO_ROOT}/src/lib/args.sh"
EDITIONS_JSON="${REPO_ROOT}/config/editions.json"
LOG_FILE="/var/log/terangaos-setup.log"

source "${REPO_ROOT}/src/lib/common.sh"

# ============================================================
# Load an edition from editions.json -> args.sh
# ============================================================
load_edition() {
    local edition="${1:-rpi}"

    if ! command -v jq &>/dev/null; then
        log_warn "jq not installed — JSON config ignored, defaults used"
        source "$ARGS_SH"
        return 0
    fi

    local config
    config=$(jq -c ".[] | select(.edition == \"${edition}\")" "$EDITIONS_JSON" 2>/dev/null)

    if [ -z "$config" ]; then
        log_error "Edition '${edition}' not found in ${EDITIONS_JSON}"
        exit 1
    fi

    log_info "Loading edition '${edition}' from editions.json..."

    # Generate args.sh dynamically (like AnduinOS)
    cat > "$ARGS_SH" << ARGS
#!/bin/bash
# Generated by setup-rpi.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Source: editions.json -> edition="${edition}"

export TERANGA_EDITION="$(echo "$config" | jq -r '.edition')"
export TERANGA_NAME="$(echo "$config" | jq -r '.name')"
export TERANGA_VERSION="0.1"
export TERANGA_CODENAME="Diamniadio"
export TERANGA_HOSTNAME="$(echo "$config" | jq -r '.hostname')"
export TERANGA_ARCH="$(echo "$config" | jq -r '.arch')"
export TERANGA_DESKTOP="$(echo "$config" | jq -r '.desktop')"
export TERANGA_THEME="$(echo "$config" | jq -r '.theme')"
export TERANGA_ICONS="$(echo "$config" | jq -r '.icons')"
export TERANGA_FONT="$(echo "$config" | jq -r '.font')"
export TERANGA_LANG="$(echo "$config" | jq -r '.lang')"
export TERANGA_TIMEZONE="$(echo "$config" | jq -r '.timezone')"
export TERANGA_KEYBOARD="$(echo "$config" | jq -r '.keyboard')"
export TERANGA_OUTPUT="$(echo "$config" | jq -r '.output_name')"
export TERANGA_WALLPAPER="dakar-sunset"
export TERANGA_CURSOR="Bibata-Modern-Classic"
ARGS

    source "$ARGS_SH"
    log_info "✓ Config loaded : THEME=${TERANGA_THEME} | LANG=${TERANGA_LANG} | HOSTNAME=${TERANGA_HOSTNAME}"
}

# ============================================================
# List available mods
# ============================================================
list_mods() {
    echo ""
    echo -e "${BLUE}${BOLD}Available TérangaOS mods:${NC}"
    echo ""
    for mod_dir in "${MODS_DIR}"/*/; do
        mod_name=$(basename "$mod_dir")
        if [ -f "${mod_dir}/install.sh" ]; then
            desc=$(grep "^# MOD" "${mod_dir}/install.sh" 2>/dev/null | \
                   sed 's/# MOD [0-9]* — //' || echo "")
            printf "  %-35s %s\n" "${mod_name}" "${desc}"
        fi
    done
    echo ""
}

# ============================================================
# Run a mod
# ============================================================
run_mod() {
    local mod_dir="$1"
    local mod_name
    mod_name=$(basename "$mod_dir")

    if [ ! -f "${mod_dir}/install.sh" ]; then
        log_warn "Mod ignored (no install.sh) : ${mod_name}"
        return 0
    fi

    local start
    start=$(date +%s)
    log_info "▶ ${mod_name}..."

    if bash "${mod_dir}/install.sh" 2>&1 | tee -a "$LOG_FILE"; then
        local duration=$(( $(date +%s) - start ))
        log_info "✓ ${mod_name} (${duration}s)"
    else
        log_error "✗ ${mod_name} failed! See: ${LOG_FILE}"
        exit 1
    fi
}

# ============================================================
# MAIN
# ============================================================
main() {
    local only_mod=""
    local do_list=false
    local edition="rpi"  # default edition

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --edition|-e) edition="$2"; shift 2 ;;
            --mod|-m)     only_mod="$2"; shift 2 ;;
            --list|-l)    do_list=true; shift ;;
            --help|-h)
                echo "Usage: sudo bash $0 [--edition rpi|desktop|leger|server] [--mod <n>] [--list]"
                echo "  --edition   Edition to install (default: rpi)"
                echo "  --mod       Run a single mod"
                echo "  --list      List available mods"
                exit 0 ;;
            *) log_error "Unknown argument: $1"; exit 1 ;;
        esac
    done

    # Root check
    if [[ $EUID -ne 0 ]]; then
        log_error "Run with sudo: sudo bash $0"
        exit 1
    fi

    touch "$LOG_FILE" 2>/dev/null || true

    # -- Load config from editions.json --
    load_edition "$edition"

    if [ "$do_list" = true ]; then
        list_mods
        exit 0
    fi

    # Banner
    echo ""
    echo -e "${GREEN}${BOLD}"
    echo "  ╔══════════════════════════════════════════════╗"
    echo "  ║                                              ║"
    echo "  ║   🇸🇳  TérangaOS — Modular Installation    ║"
    printf "  ║   %-44s║\n" "${TERANGA_NAME} — v${TERANGA_VERSION}"
    echo "  ║                                              ║"
    echo "  ╚══════════════════════════════════════════════╝"
    echo -e "${NC}"

    local start_total
    start_total=$(date +%s)

    if [ -n "$only_mod" ]; then
        # Run a single mod
        local found=false
        for mod_dir in "${MODS_DIR}"/*/; do
            if [[ "$(basename "$mod_dir")" == "${only_mod}"* ]]; then
                run_mod "$mod_dir"
                found=true
                break
            fi
        done
        if [ "$found" = false ]; then
            log_error "Mod '${only_mod}' not found. Use --list to see mods."
            exit 1
        fi
    else
        # Full installation confirmation
        echo -e "${YELLOW}This script will transform your RPi into TérangaOS.${NC}"
        echo -e "${YELLOW}Estimated duration: 30-60 minutes depending on connection.${NC}"
        echo ""
        read -p "Continue? (y/N) " -n 1 -r; echo
        [[ ! $REPLY =~ ^[Yy]$ ]] && echo "Cancelled." && exit 0

        # Run all mods in order
        for mod_dir in "${MODS_DIR}"/*/; do
            run_mod "$mod_dir"
        done
    fi

    local duration=$(( ($(date +%s) - start_total) / 60 ))
    echo ""
    echo -e "${GREEN}${BOLD}"
    echo "  ╔══════════════════════════════════════════════╗"
    echo "  ║   ✅ Installation complete in ${duration} min        ║"
    echo "  ║                                              ║"
    echo "  ║   → sudo reboot  to restart             ║"
    echo "  ║   → Ndank ndank mooy jàpp golo ci ñaay 🌍   ║"
    echo "  ╚══════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo "  Full log: ${LOG_FILE}"
}

main "$@"
